version: '3.8'

services:

  # -----------------------------
  # Log Vizualization 
  # -----------------------------
  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana
    hostname: kibana
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      - ELASTICSEARCH_URL=http://localhost:9200
    links:
      - elasticsearch
    networks:
      - backend

  # -----------------------------
  # Indexing Server
  # -----------------------------
  elasticsearch:
    image: elasticsearch:${ELK_VERSION}
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.seed_hosts=localhost"
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    expose:
      - "9200"
    networks:
      - backend

  # -----------------------------
  # Log Collection and Format
  # -----------------------------
  logstash:
    image: logstash:${ELK_VERSION}
    container_name: log-stash
    hostname: localhost
    ports:
      - "5000:5000"
    expose:
      - "5000"
    volumes:
      - /logs:/tmp/
    command: >
      logstash --debug -e 'input { tcp { port => 5000 codec => json { charset => "UTF-8" } } } output { elasticsearch { hosts => "elasticsearch:9200" } }'
    depends_on:
      - elasticsearch
    networks:
      - backend

  news-search:
    build: 
        dockerfile: Dockerfile
    container_name: news-search
    image: news-search:latest
    ports:
    - 8080:8080

networks:
  backend:
    driver: bridge

volumes:
  mongodata:
